# Generated by Django 4.2.5 on 2023-10-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_management_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="year",
            field=models.IntegerField(default="3"),
            preserve_default=False,
        ),
    ]
