# Generated by Django 4.2.5 on 2023-10-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "student_management_app",
            "0004_alter_student_year",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
