# Generated by Django 4.2.5 on 2023-10-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "group_management_app",
            "0002_alter_group_curator",
        ),
        (
            "student_management_app",
            "0005_student_phone_number",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="group",
            field=models.ManyToManyField(
                related_name="students",
                to="group_management_app.group",
            ),
        ),
    ]
