# Generated by Django 4.2.5 on 2023-10-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "student_management_app",
            "0007_alter_student_group",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="test",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
