# Generated by Django 4.2.5 on 2023-10-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_management_app", "0008_student_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="test",
        ),
        migrations.AlterField(
            model_name="student",
            name="year",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
