# Generated by Django 4.2.1 on 2023-10-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher_management_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="patronymic",
            field=models.CharField(default="Not defined", max_length=150),
            preserve_default=False,
        ),
    ]
