# Generated by Django 4.2.5 on 2023-10-04 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher_management_app", "0001_initial"),
        ("group_management_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="curator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="teacher_management_app.teacher",
            ),
        ),
    ]
